In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [34]:
cluster0 = pd.read_csv('cluster0.csv').drop('Unnamed: 0',axis=1)
# cluster1 = pd.read_csv('cluster1.csv').drop('Unnamed: 0',axis=1)
# cluster2 = pd.read_csv('cluster2.csv').drop('Unnamed: 0',axis=1)
# cluster3 = pd.read_csv('cluster3.csv').drop('Unnamed: 0',axis=1)
# cluster4 = pd.read_csv('cluster4.csv').drop('Unnamed: 0',axis=1)
# cluster5 = pd.read_csv('cluster5.csv').drop('Unnamed: 0',axis=1)

In [36]:
products = pd.read_csv('products.csv')

In [4]:
cluster0.shape

(7354493, 13)

### Cluster 0 - Basket Analysis

In [37]:
prod_freq = cluster0.groupby('product_id')['order_id'].count().reset_index()
prod_freq = prod_freq.rename(columns = {'order_id':'frequency'})
prod_freq = prod_freq.sort_values('frequency', ascending=False).reset_index(drop=True)
prod_freq = prod_freq.merge(products, on = 'product_id', how = 'left')
prod_freq

,product_id,frequency,product_name,aisle_id,department_id
0,24852,99641,Banana,24,4
1,21903,86029,Organic Baby Spinach,123,4
2,13176,84010,Bag of Organic Bananas,24,4
3,47209,66210,Organic Hass Avocado,24,4
4,21137,61536,Organic Strawberries,24,4
...,...,...,...,...,...
38480,16422,1,Cherry Limeade Flavored Fruit Drink,31,7
38481,16433,1,Ham & Cheese Loaf,96,20
38482,16438,1,Unsulphured Robust Molasses,29,13
38483,16443,1,Special K Chocolate Peanut Butter Bar,3,19
38484,1,1,Chocolate Sandwich Cookies,61,19

In [38]:
# only keeping the 100 most purchased products
prod_freq = prod_freq[0:100]
prod_freq_prod = list(prod_freq['product_id'])
len(prod_freq_prod)

100

In [39]:
# filter main cluster dataset only on the 100 most purchases products
cluster0 = cluster0[cluster0['product_id'].isin(prod_freq_prod)]
print(cluster0.shape)
cluster0['product_id'].nunique()

(2518676, 13)

100

In [40]:
cluster0.order_id.nunique()

593120

In [41]:
basket_0 = cluster0.groupby(['order_id', 'product_name'])['reordered'].count().unstack().reset_index().fillna(0).set_index('order_id')
basket_0.head()

product_name,Apple Honeycrisp Organic,Asparagus,Bag of Organic Bananas,Banana,Boneless Skinless Chicken Breasts,Broccoli Crown,Brussels Sprouts,Bunched Cilantro,Carrots,Cucumber Kirby,...,Seedless Red Grapes,Shredded Parmesan,Small Hass Avocado,Sparkling Water Grapefruit,Spring Water,Strawberries,Unsalted Butter,Unsweetened Almondmilk,Yellow Bell Pepper,Yellow Onions
order_id,,,,,,,,,,,,,,,,,,,,,
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
18,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [42]:
# in order to use the the above frequency counts in the apriori algorithm I need to one hot encode them
def encode_basket(x):
    if x <= 0:
        return 0
    else:
        return 1

basket_0 = basket_0.applymap(encode_basket)

In [43]:
basket_0.head()

product_name,Apple Honeycrisp Organic,Asparagus,Bag of Organic Bananas,Banana,Boneless Skinless Chicken Breasts,Broccoli Crown,Brussels Sprouts,Bunched Cilantro,Carrots,Cucumber Kirby,...,Seedless Red Grapes,Shredded Parmesan,Small Hass Avocado,Sparkling Water Grapefruit,Spring Water,Strawberries,Unsalted Butter,Unsweetened Almondmilk,Yellow Bell Pepper,Yellow Onions
order_id,,,,,,,,,,,,,,,,,,,,,
2,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
18,0,1,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
19,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
23,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [44]:
basket_0.shape

(593120, 100)

In [45]:
itemset0 = apriori(basket_0, use_colnames=True, verbose=1, min_support=0.021)

Processing 105 combinations | Sampling itemset size 32

In [46]:
itemset0

     support                                      itemsets
0   0.035829                    (Apple Honeycrisp Organic)
1   0.055512                                   (Asparagus)
2   0.141641                      (Bag of Organic Bananas)
3   0.167995                                      (Banana)
4   0.034276           (Boneless Skinless Chicken Breasts)
..       ...                                           ...
89  0.026189                     (Organic Avocado, Banana)
90  0.029808                (Organic Baby Spinach, Banana)
91  0.021326       (Organic Avocado, Organic Baby Spinach)
92  0.021684  (Organic Hass Avocado, Organic Baby Spinach)
93  0.022130        (Organic Garlic, Organic Yellow Onion)

[94 rows x 2 columns]

In [47]:
rules0 = association_rules(itemset0, metric="lift", min_threshold=1)
rules0.sort_values(['confidence','lift'], ascending=[False,False])

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
6,(Cucumber Kirby),(Banana),0.072247,0.167995,0.021062,0.291522,1.735304,0.008924,1.174356
2,(Organic Hass Avocado),(Bag of Organic Bananas),0.111630,0.141641,0.029326,0.262710,1.854759,0.013515,1.164208
10,(Organic Avocado),(Banana),0.099821,0.167995,0.026189,0.262355,1.561687,0.009419,1.127921
9,(Large Lemon),(Banana),0.097510,0.167995,0.022596,0.231728,1.379378,0.006215,1.082957
19,(Organic Yellow Onion),(Organic Garlic),0.095731,0.100706,0.022130,0.231173,2.295513,0.012490,1.169696
18,(Organic Garlic),(Organic Yellow Onion),0.100706,0.095731,0.022130,0.219752,2.295513,0.012490,1.158951
4,(Organic Strawberries),(Bag of Organic Bananas),0.103750,0.141641,0.022540,0.217255,1.533844,0.007845,1.096601
14,(Organic Avocado),(Organic Baby Spinach),0.099821,0.145045,0.021326,0.213644,1.472951,0.006848,1.087237
3,(Bag of Organic Bananas),(Organic Hass Avocado),0.141641,0.111630,0.029326,0.207047,1.854759,0.013515,1.120331
12,(Organic Baby Spinach),(Banana),0.145045,0.167995,0.029808,0.205512,1.223325,0.005442,1.047222
16,(Organic Hass Avocado),(Organic Baby Spinach),0.111630,0.145045,0.021684,0.194246,1.339210,0.005492,1.061062
1,(Bag of Organic Bananas),(Organic Baby Spinach),0.141641,0.145045,0.027043,0.190930,1.316349,0.006499,1.056713
0,(Organic Baby Spinach),(Bag of Organic Bananas),0.145045,0.141641,0.027043,0.186449,1.316349,0.006499,1.055077
13,(Banana),(Organic Baby Spinach),0.167995,0.145045,0.029808,0.177437,1.223325,0.005442,1.039380
5,(Bag of Organic Bananas),(Organic Strawberries),0.141641,0.103750,0.022540,0.159136,1.533844,0.007845,1.065868
11,(Banana),(Organic Avocado),0.167995,0.099821,0.026189,0.155890,1.561687,0.009419,1.066423
17,(Organic Baby Spinach),(Organic Hass Avocado),0.145045,0.111630,0.021684,0.149496,1.339210,0.005492,1.044522
15,(Organic Baby Spinach),(Organic Avocado),0.145045,0.099821,0.021326,0.147032,1.472951,0.006848,1.055349
8,(Banana),(Large Lemon),0.167995,0.097510,0.022596,0.134503,1.379378,0.006215,1.042742
7,(Banana),(Cucumber Kirby),0.167995,0.072247,0.021062,0.125370,1.735304,0.008924,1.060738

In [15]:
rules0.to_csv('basket0.csv')

### Cluster 1 - Basket Analysis

In [16]:
prod_freq1 = cluster1.groupby('product_id')['order_id'].count().reset_index()
prod_freq1 = prod_freq1.rename(columns = {'order_id':'frequency'})
prod_freq1 = prod_freq1.sort_values('frequency', ascending=False).reset_index(drop=True)
prod_freq1 = prod_freq1.merge(products, on = 'product_id', how = 'left')
prod_freq1

,product_id,frequency,product_name,aisle_id,department_id
0,24852,54637,Banana,24,4
1,13176,50581,Bag of Organic Bananas,24,4
2,21137,32089,Organic Strawberries,24,4
3,47209,20625,Organic Hass Avocado,24,4
4,16797,19755,Strawberries,24,4
...,...,...,...,...,...
24809,31908,1,Beef Rib Roast,122,12
24810,31905,1,Single-Grain Rice Cereal,92,18
24811,31903,1,"Sweetener, Liquid Stevia, Chocolate",97,13
24812,31901,1,Mineral Sun Spray Lotion Broad Spectrum SPF 30...,25,11
24813,49688,1,Fresh Foaming Cleanser,73,11

In [17]:
# only keeping the 100 most purchased products
prod_freq1 = prod_freq1[0:100]
prod_freq_prod1 = list(prod_freq1['product_id'])

In [18]:
# filter main cluster dataset only on the 100 most purchases products
cluster1 = cluster1[cluster1['product_id'].isin(prod_freq_prod1)]
print(cluster1.shape)
cluster1['product_id'].nunique()

(645303, 13)

100

In [19]:
basket_1 = cluster1.groupby(['order_id', 'product_name'])['reordered'].count().unstack().reset_index().fillna(0).set_index('order_id')

In [20]:
# in order to use the the above frequency counts in the apriori algorithm I need to one hot encode them

basket_1 = basket_1.applymap(encode_basket)

In [21]:
itemset1 = apriori(basket_1, use_colnames=True, verbose=1, min_support=0.007)

Processing 4 combinations | Sampling itemset size 4e 3

In [22]:
rules1 = association_rules(itemset1, metric="lift", min_threshold=1)
rules1.sort_values(['confidence','lift'], ascending=[False,False])

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
200,"(Organic Hass Avocado, Organic Raspberries)",(Bag of Organic Bananas),0.013919,0.258371,0.007044,0.506055,1.958638,0.003448,1.501441
83,(Organic Fuji Apple),(Banana),0.075415,0.279089,0.036926,0.489637,1.754411,0.015879,1.412545
53,"(Clementines, Bag)",(Banana),0.024279,0.279089,0.011422,0.470440,1.685625,0.004646,1.361339
54,(Cucumber Kirby),(Banana),0.032268,0.279089,0.014967,0.463828,1.661934,0.005961,1.344551
57,(Gala Apples),(Banana),0.023165,0.279089,0.010717,0.462624,1.657621,0.004252,1.341539
...,...,...,...,...,...,...,...,...,...
13,(Bag of Organic Bananas),(Hass Avocados),0.258371,0.019349,0.007049,0.027283,1.410021,0.002050,1.008156
205,(Bag of Organic Bananas),"(Organic Hass Avocado, Organic Raspberries)",0.258371,0.013919,0.007044,0.027263,1.958638,0.003448,1.013718
222,(Banana),"(Organic Strawberries, Organic Avocado)",0.279089,0.017495,0.007509,0.026905,1.537850,0.002626,1.009670
92,(Banana),(Organic Peeled Whole Baby Carrots),0.279089,0.018103,0.007458,0.026722,1.476101,0.002405,1.008855
68,(Banana),(Large Yellow Flesh Nectarine),0.279089,0.017311,0.007202,0.025807,1.490749,0.002371,1.008721

In [23]:
final_products = list()

for prod in rules1['antecedents'].values:
    products = str()
    for prod_2 in prod:
        products += prod_2 +  ' '
    final_products.append(products)

In [24]:
rules1['antecedents_1'] = final_products

In [25]:
final_products_con = list()

for prod_con in rules1['consequents'].values:
    products_con = str()
    for prod_2_con in prod_con:
        products_con += prod_2_con +  ' '
    final_products_con.append(products_con)

In [26]:
rules1['consequents_1'] = final_products_con

In [27]:
rules1 = rules1[['antecedents_1','consequents_1','antecedent support','consequent support','support','confidence','lift','leverage','conviction']]
rules1 = rules1.rename(columns={'antecedents_1':'antecedents','consequents_1':'consequents'})
rules1 = rules1.sort_values(['confidence','lift'], ascending=[False,False])
rules1

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
200,Organic Hass Avocado Organic Raspberries,Bag of Organic Bananas,0.013919,0.258371,0.007044,0.506055,1.958638,0.003448,1.501441
83,Organic Fuji Apple,Banana,0.075415,0.279089,0.036926,0.489637,1.754411,0.015879,1.412545
53,"Clementines, Bag",Banana,0.024279,0.279089,0.011422,0.470440,1.685625,0.004646,1.361339
54,Cucumber Kirby,Banana,0.032268,0.279089,0.014967,0.463828,1.661934,0.005961,1.344551
57,Gala Apples,Banana,0.023165,0.279089,0.010717,0.462624,1.657621,0.004252,1.341539
...,...,...,...,...,...,...,...,...,...
13,Bag of Organic Bananas,Hass Avocados,0.258371,0.019349,0.007049,0.027283,1.410021,0.002050,1.008156
205,Bag of Organic Bananas,Organic Hass Avocado Organic Raspberries,0.258371,0.013919,0.007044,0.027263,1.958638,0.003448,1.013718
222,Banana,Organic Strawberries Organic Avocado,0.279089,0.017495,0.007509,0.026905,1.537850,0.002626,1.009670
92,Banana,Organic Peeled Whole Baby Carrots,0.279089,0.018103,0.007458,0.026722,1.476101,0.002405,1.008855
68,Banana,Large Yellow Flesh Nectarine,0.279089,0.017311,0.007202,0.025807,1.490749,0.002371,1.008721

In [48]:
rules1[:60]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
200,Organic Hass Avocado Organic Raspberries,Bag of Organic Bananas,0.013919,0.258371,0.007044,0.506055,1.958638,0.003448,1.501441
83,Organic Fuji Apple,Banana,0.075415,0.279089,0.036926,0.489637,1.754411,0.015879,1.412545
53,"Clementines, Bag",Banana,0.024279,0.279089,0.011422,0.470440,1.685625,0.004646,1.361339
54,Cucumber Kirby,Banana,0.032268,0.279089,0.014967,0.463828,1.661934,0.005961,1.344551
57,Gala Apples,Banana,0.023165,0.279089,0.010717,0.462624,1.657621,0.004252,1.341539
65,Honeycrisp Apple,Banana,0.059054,0.279089,0.027308,0.462417,1.656878,0.010826,1.341022
59,Granny Smith Apples,Banana,0.036058,0.279089,0.016136,0.447514,1.603480,0.006073,1.304849
49,Bartlett Pears,Banana,0.041013,0.279089,0.018210,0.444015,1.590945,0.006764,1.296638
63,Half & Half,Banana,0.024340,0.279089,0.010543,0.433158,1.552043,0.003750,1.271803
219,Organic Strawberries Organic Avocado,Banana,0.017495,0.279089,0.007509,0.429197,1.537850,0.002626,1.262977
207,Organic Strawberries Organic Hass Avocado,Bag of Organic Bananas,0.025418,0.258371,0.010880,0.428055,1.656745,0.004313,1.296678
69,Large Yellow Flesh Nectarine,Banana,0.017311,0.279089,0.007202,0.416052,1.490749,0.002371,1.234546
93,Organic Peeled Whole Baby Carrots,Banana,0.018103,0.279089,0.007458,0.411964,1.476101,0.002405,1.225964
101,Small Hass Avocado,Banana,0.022327,0.279089,0.009189,0.411576,1.474713,0.002958,1.225156
72,Organic Avocado,Banana,0.093120,0.279089,0.037922,0.407241,1.459178,0.011933,1.216195
96,Original Hummus,Banana,0.020892,0.279089,0.008423,0.403178,1.444623,0.002592,1.207917
212,Organic Strawberries Organic Raspberries,Bag of Organic Bananas,0.019150,0.258371,0.007514,0.392371,1.518636,0.002566,1.220530
38,Organic Navel Orange,Bag of Organic Bananas,0.036364,0.258371,0.014175,0.389802,1.508692,0.004779,1.215391
67,Large Lemon,Banana,0.071298,0.279089,0.027543,0.386302,1.384152,0.007644,1.174699
51,Blueberries,Banana,0.023109,0.279089,0.008914,0.385721,1.382070,0.002464,1.173588
99,Seedless Red Grapes,Banana,0.047239,0.279089,0.017996,0.380947,1.364966,0.004812,1.164539
30,Organic Hass Avocado,Bag of Organic Bananas,0.105354,0.258371,0.039971,0.379394,1.468409,0.012750,1.195008
10,Clementines,Bag of Organic Bananas,0.032462,0.258371,0.012183,0.375295,1.452544,0.003796,1.187167
61,Grape White/Green Seedless,Banana,0.034459,0.279089,0.012668,0.367625,1.317232,0.003051,1.140006
12,Hass Avocados,Bag of Organic Bananas,0.019349,0.258371,0.007049,0.364308,1.410021,0.002050,1.166649
36,Organic Lemon,Bag of Organic Bananas,0.040660,0.258371,0.014727,0.362186,1.401807,0.004221,1.162767
40,Organic Raspberries,Bag of Organic Bananas,0.057415,0.258371,0.020785,0.362011,1.401128,0.005950,1.162448
214,Organic Raspberries Bag of Organic Bananas,Organic Strawberries,0.020785,0.163913,0.007514,0.361514,2.205529,0.004107,1.309484
35,Organic Large Extra Fancy Fuji Apple,Bag of Organic Bananas,0.052843,0.258371,0.018123,0.342968,1.327424,0.004470,1.128756
94,Organic Whole Milk,Banana,0.046907,0.279089,0.016039,0.341936,1.225186,0.002948,1.095503
22,Organic Cucumber,Bag of Organic Bananas,0.022853,0.258371,0.007780,0.340411,1.317530,0.001875,1.124381
202,Organic Raspberries Bag of Organic Bananas,Organic Hass Avocado,0.020785,0.105354,0.007044,0.338904,3.216818,0.004854,1.353277
70,Limes,Banana,0.052373,0.279089,0.017592,0.335902,1.203564,0.002975,1.085548
191,Organic Raspberries,Organic Strawberries,0.057415,0.163913,0.019150,0.333541,2.034871,0.009739,1.254522
89,Organic Grape Tomatoes,Banana,0.025673,0.279089,0.008546,0.332869,1.192698,0.001381,1.080614
8,Apples,Clementines,0.025576,0.032462,0.008403,0.328540,10.120843,0.007573,1.440947
107,Blackberries,Strawberries,0.023834,0.100910,0.007820,0.328118,3.251602,0.005415,1.338168
79,Organic Blackberries,Banana,0.047439,0.279089,0.015477,0.326263,1.169026,0.002238,1.070017
25,Organic D'Anjou Pears,Bag of Organic Bananas,0.041953,0.258371,0.013536,0.322659,1.248822,0.002697,1.094913
0,Apple Honeycrisp Organic,Bag of Organic Bananas,0.052674,0.258371,0.016913,0.321082,1.242719,0.003303,1.092370
20,Organic Blueberries,Bag of Organic Bananas,0.054917,0.258371,0.017327,0.315506,1.221134,0.003138,1.083470
103,Strawberries,Banana,0.100910,0.279089,0.031180,0.308985,1.107120,0.003017,1.043264
18,Organic Bartlett Pear,Bag of Organic Bananas,0.030975,0.258371,0.009532,0.307718,1.190992,0.001529,1.071281
26,Organic Gala Apples,Bag of Organic Bananas,0.054054,0.258371,0.016632,0.307692,1.190894,0.002666,1.071242
81,Organic D'Anjou Pears,Banana,0.041953,0.279089,0.012883,0.307074,1.100273,0.001174,1.040387
196,Raspberries,Strawberries,0.035302,0.100910,0.010778,0.305310,3.025579,0.007216,1.294233
177,Organic Lemon,Organic Hass Avocado,0.040660,0.105354,0.012387,0.304648,2.891669,0.008103,1.286610
33,Organic Kiwi,Bag of Organic Bananas,0.045916,0.258371,0.013873,0.302147,1.169432,0.002010,1.062730
16,Organic Baby Spinach,Bag of Organic Bananas,0.080677,0.258371,0.024253,0.300620,1.163523,0.003409,1.060410
6,Apples,Bag of Organic Bananas,0.025576,0.258371,0.007688,0.300579,1.163363,0.001080,1.060348
157,Organic Blueberries,Organic Strawberries,0.054917,0.163913,0.016473,0.299972,1.830074,0.007472,1.194363
91,Organic Half & Half,Banana,0.030541,0.279089,0.008980,0.294029,1.053531,0.000456,1.021162
85,Organic Gala Apples,Banana,0.054054,0.279089,0.015850,0.293234,1.050682,0.000765,1.020013
42,Organic Strawberries,Bag of Organic Bananas,0.163913,0.258371,0.047525,0.289944,1.122199,0.005175,1.044465
14,Organic Baby Carrots,Bag of Organic Bananas,0.033923,0.258371,0.009746,0.287306,1.111991,0.000982,1.040600
76,Organic Bartlett Pear,Banana,0.030975,0.279089,0.008868,0.286280,1.025764,0.000223,1.010075
86,Organic Granny Smith Apple,Banana,0.045758,0.279089,0.012842,0.280643,1.005568,0.000071,1.002160
74,Organic Baby Spinach,Banana,0.080677,0.279089,0.022603,0.280170,1.003872,0.000087,1.001501
28,Organic Granny Smith Apple,Bag of Organic Bananas,0.045758,0.258371,0.012683,0.277182,1.072808,0.000861,1.026025
46,Raspberries,Bag of Organic Bananas,0.035302,0.258371,0.009705,0.274924,1.064068,0.000584,1.022830

In [28]:
rules1[rules1['antecedents'].str.contains('Clementine')]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
53,"Clementines, Bag",Banana,0.024279,0.279089,0.011422,0.470440,1.685625,0.004646,1.361339
10,Clementines,Bag of Organic Bananas,0.032462,0.258371,0.012183,0.375295,1.452544,0.003796,1.187167
9,Clementines,Apples,0.032462,0.025576,0.008403,0.258851,10.120843,0.007573,1.314748

In [23]:
rules1.to_csv('basket1.csv',index=False)

### Cluster 2 - Basket Analysis

In [4]:
prod_freq2 = cluster2.groupby('product_id')['order_id'].count().reset_index()
prod_freq2 = prod_freq2.rename(columns = {'order_id':'frequency'})
prod_freq2 = prod_freq2.sort_values('frequency', ascending=False).reset_index(drop=True)
prod_freq2 = prod_freq2.merge(products, on = 'product_id', how = 'left')

In [5]:
# only keeping the 100 most purchased products
prod_freq2 = prod_freq2[0:100]
prod_freq_prod2 = list(prod_freq2['product_id'])

In [6]:
# filter main cluster dataset only on the 100 most purchases products
cluster2 = cluster2[cluster2['product_id'].isin(prod_freq_prod2)]
print(cluster2.shape)
cluster2['product_id'].nunique()

(966162, 13)

100

In [7]:
basket_2 = cluster2.groupby(['order_id', 'product_name'])['reordered'].count().unstack().reset_index().fillna(0).set_index('order_id')

In [8]:
def encode_basket(x):
    if x <= 0:
        return 0
    else:
        return 1

basket_2 = basket_2.applymap(encode_basket)

In [9]:
itemset2 = apriori(basket_2, use_colnames=True, verbose=1, min_support=0.0109)

Processing 8372 combinations | Sampling itemset size 2

In [10]:
itemset2

     support                                          itemsets
0   0.014306                          (100% Raw Coconut Water)
1   0.035288                          (100% Whole Wheat Bread)
2   0.040095                             (2% Reduced Fat Milk)
3   0.071607                          (Bag of Organic Bananas)
4   0.128736                                          (Banana)
..       ...                                               ...
87  0.015966  (Unsweetened Original Almond Breeze Almond Milk)
88  0.012194                 (Unsweetened Vanilla Almond Milk)
89  0.014760               (Vanilla Almond Breeze Almond Milk)
90  0.028970                                      (Whole Milk)
91  0.014985                                   (Yellow Onions)

[92 rows x 2 columns]

In [11]:
rules2 = association_rules(itemset2, metric="lift", min_threshold=0.5)
rules2.sort_values(['confidence','lift'], ascending=[False,False])

Empty DataFrame
Columns: [antecedents, consequents, antecedent support, consequent support, support, confidence, lift, leverage, conviction]
Index: []

In [56]:
rules2 = pd.read_csv('basket2.csv')
rules2.sort_values(['confidence','lift'], ascending=[False,False])[:10]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
522,"frozenset({'Pure Sparkling Water', 'Sparkling ...",frozenset({'Sparkling Water Grapefruit'}),0.001756,0.030695,0.001009,0.574468,18.715641,0.000955,2.277868
516,"frozenset({'Sparkling Lemon Water', 'Lime Spar...",frozenset({'Sparkling Water Grapefruit'}),0.004127,0.030695,0.001937,0.469271,15.288420,0.001810,1.826366
518,"frozenset({'Sparkling Lemon Water', 'Sparkling...",frozenset({'Lime Sparkling Water'}),0.004448,0.021231,0.001937,0.435455,20.510197,0.001842,1.733731
523,"frozenset({'Pure Sparkling Water', 'Sparkling ...",frozenset({'Sparkling Lemon Water'}),0.003048,0.017340,0.001009,0.330968,19.086920,0.000956,1.468778
517,"frozenset({'Lime Sparkling Water', 'Sparkling ...",frozenset({'Sparkling Lemon Water'}),0.005991,0.017340,0.001937,0.323269,18.642921,0.001833,1.452068
232,frozenset({'Organic Fuji Apple'}),frozenset({'Banana'}),0.021713,0.128736,0.006520,0.300281,2.332535,0.003725,1.245162
394,frozenset({'Lime Sparkling Water'}),frozenset({'Sparkling Water Grapefruit'}),0.021231,0.030695,0.005991,0.282182,9.193226,0.005339,1.350350
203,frozenset({'Honeycrisp Apple'}),frozenset({'Banana'}),0.010631,0.128736,0.002814,0.264657,2.055814,0.001445,1.184840
508,frozenset({'Sparkling Lemon Water'}),frozenset({'Sparkling Water Grapefruit'}),0.017340,0.030695,0.004448,0.256492,8.356262,0.003915,1.303691
507,frozenset({'Trail Mix'}),frozenset({'Soda'}),0.013602,0.045716,0.003297,0.242411,5.302497,0.002675,1.259632

### Cluster 3 - Basket Analysis

In [48]:
prod_freq3 = cluster3.groupby('product_id')['order_id'].count().reset_index()
prod_freq3 = prod_freq3.rename(columns = {'order_id':'frequency'})
prod_freq3 = prod_freq3.sort_values('frequency', ascending=False).reset_index(drop=True)
prod_freq3 = prod_freq3.merge(products, on = 'product_id', how = 'left')

In [49]:
# only keeping the 100 most purchased products
prod_freq3 = prod_freq3[0:100]
prod_freq_prod3 = list(prod_freq3['product_id'])

In [50]:
# filter main cluster dataset only on the 100 most purchases products
cluster3 = cluster3[cluster3['product_id'].isin(prod_freq_prod3)]
print(cluster3.shape)
cluster3['product_id'].nunique()

(127749, 13)

100

In [51]:
basket_3 = cluster3.groupby(['order_id', 'product_name'])['reordered'].count().unstack().reset_index().fillna(0).set_index('order_id')

In [52]:
basket_3 = basket_3.applymap(encode_basket)

In [57]:
itemset3 = apriori(basket_3, use_colnames=True, verbose=1, min_support=0.002)

Processing 70 combinations | Sampling itemset size 76 5

In [58]:
itemset3

       support                                           itemsets
0     0.008699                         (0% Greek Strained Yogurt)
1     0.007478                                          (1 Liter)
2     0.009357                        (100% Natural Spring Water)
3     0.006970                           (100% Raw Coconut Water)
4     0.007102                              (2% Reduced Fat Milk)
...        ...                                                ...
1391  0.002029  (Kiwi Sandia Sparkling Water, Curate Melon Pom...
1392  0.002255  (Kiwi Sandia Sparkling Water, Curate Melon Pom...
1393  0.002048  (Kiwi Sandia Sparkling Water, Curate Melon Pom...
1394  0.002029  (Kiwi Sandia Sparkling Water, Sparkling Water ...
1395  0.002104  (Kiwi Sandia Sparkling Water, Curate Melon Pom...

[1396 rows x 2 columns]

In [59]:
rules3 = association_rules(itemset3, metric="lift", min_threshold=0.5)
rules3.sort_values(['confidence','lift'], ascending=[False,False])

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
3659,"(All Natural Apricot Sparkling Water, Sparklin...",(Sparkling Water Grapefruit),0.002255,0.150568,0.002198,0.975000,6.475465,0.001859,33.977266
7593,"(Organic Fuji Apple, Sparkling Water Berry, Pu...",(Sparkling Water Grapefruit),0.002123,0.150568,0.002067,0.973451,6.465179,0.001747,31.995259
7852,"(Lime Sparkling Water, All Natural Apricot Spa...",(Sparkling Water Grapefruit),0.002649,0.150568,0.002574,0.971631,6.453091,0.002175,29.942466
7942,"(Peach Pear Flavored Sparkling Water, All Natu...",(Sparkling Water Grapefruit),0.002893,0.150568,0.002781,0.961039,6.382743,0.002345,21.802079
3560,"(Lime Sparkling Water, All Natural Apricot Spa...",(Sparkling Water Grapefruit),0.004133,0.150568,0.003946,0.954545,6.339616,0.003323,18.687496
...,...,...,...,...,...,...,...,...,...
3446,(Sparkling Water Grapefruit),"(Peach Pear Flavored Sparkling Water, Kiwi San...",0.150568,0.002255,0.002010,0.013352,5.922006,0.001671,1.011247
7269,(Sparkling Water Grapefruit),"(Lime Sparkling Water, Sparkling Lemon Water, ...",0.150568,0.002292,0.002010,0.013352,5.824924,0.001665,1.011209
13007,(Sparkling Water Grapefruit),"(Curate Melon Pomelo Sparking Water, Sparkling...",0.150568,0.002330,0.002010,0.013352,5.730974,0.001660,1.011171
8023,(Sparkling Water Grapefruit),"(Lime Sparkling Water, Peach Pear Flavored Spa...",0.150568,0.002349,0.002010,0.013352,5.685126,0.001657,1.011152
3391,(Sparkling Water Grapefruit),"(All Natural Apricot Sparkling Water, Curate M...",0.150568,0.002480,0.002010,0.013352,5.383642,0.001637,1.011019

In [60]:
rules3.to_csv('basket3.csv',index=False)

### Cluster 4 - Basket Analysis

In [4]:
prod_freq4 = cluster4.groupby('product_id')['order_id'].count().reset_index()
prod_freq4 = prod_freq4.rename(columns = {'order_id':'frequency'})
prod_freq4 = prod_freq4.sort_values('frequency', ascending=False).reset_index(drop=True)
prod_freq4 = prod_freq4.merge(products, on = 'product_id', how = 'left')

In [5]:
# only keeping the 100 most purchased products
prod_freq4 = prod_freq4[0:100]
prod_freq_prod4 = list(prod_freq4['product_id'])

In [6]:
# filter main cluster dataset only on the 100 most purchases products
cluster4 = cluster4[cluster4['product_id'].isin(prod_freq_prod4)]
print(cluster4.shape)
cluster4['product_id'].nunique()

(3583719, 13)

100

In [7]:
basket_4 = cluster4.groupby(['order_id', 'product_name'])['reordered'].count().unstack().reset_index().fillna(0).set_index('order_id')

In [8]:
def encode_basket(x):
    if x <= 0:
        return 0
    else:
        return 1

basket_4 = basket_4.applymap(encode_basket)

In [9]:
itemset4 = apriori(basket_4, use_colnames=True, verbose=1, min_support=0.022)

Processing 63 combinations | Sampling itemset size 3 2

In [10]:
itemset4

     support                                      itemsets
0   0.030351                      (100% Whole Wheat Bread)
1   0.047038                    (Apple Honeycrisp Organic)
2   0.025713                                   (Asparagus)
3   0.182874                      (Bag of Organic Bananas)
4   0.240262                                      (Banana)
..       ...                                           ...
61  0.027466                     (Organic Avocado, Banana)
62  0.026954                (Organic Baby Spinach, Banana)
63  0.032585                (Organic Strawberries, Banana)
64  0.022392                        (Banana, Strawberries)
65  0.023450  (Organic Hass Avocado, Organic Strawberries)

[66 rows x 2 columns]

In [11]:
rules4 = association_rules(itemset4, metric="lift", min_threshold=0.5)
rules4.sort_values(['confidence','lift'], ascending=[False,False])

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
15,(Strawberries),(Banana),0.061449,0.240262,0.022392,0.364390,1.516638,0.007628,1.195290
8,(Organic Avocado),(Banana),0.084122,0.240262,0.027466,0.326503,1.358945,0.007255,1.128049
4,(Organic Raspberries),(Bag of Organic Bananas),0.076729,0.182874,0.023962,0.312293,1.707697,0.009930,1.188189
2,(Organic Hass Avocado),(Bag of Organic Bananas),0.109360,0.182874,0.033962,0.310552,1.698179,0.013963,1.185190
6,(Organic Strawberries),(Bag of Organic Bananas),0.142823,0.182874,0.034470,0.241346,1.319742,0.008351,1.077074
10,(Organic Baby Spinach),(Banana),0.112425,0.240262,0.026954,0.239755,0.997891,-0.000057,0.999333
12,(Organic Strawberries),(Banana),0.142823,0.240262,0.032585,0.228147,0.949577,-0.001730,0.984304
0,(Organic Baby Spinach),(Bag of Organic Bananas),0.112425,0.182874,0.025378,0.225728,1.234340,0.004818,1.055348
16,(Organic Hass Avocado),(Organic Strawberries),0.109360,0.142823,0.023450,0.214431,1.501368,0.007831,1.091153
7,(Bag of Organic Bananas),(Organic Strawberries),0.182874,0.142823,0.034470,0.188490,1.319742,0.008351,1.056274
3,(Bag of Organic Bananas),(Organic Hass Avocado),0.182874,0.109360,0.033962,0.185714,1.698179,0.013963,1.093767
17,(Organic Strawberries),(Organic Hass Avocado),0.142823,0.109360,0.023450,0.164190,1.501368,0.007831,1.065601
1,(Bag of Organic Bananas),(Organic Baby Spinach),0.182874,0.112425,0.025378,0.138771,1.234340,0.004818,1.030591
13,(Banana),(Organic Strawberries),0.240262,0.142823,0.032585,0.135622,0.949577,-0.001730,0.991669
5,(Bag of Organic Bananas),(Organic Raspberries),0.182874,0.076729,0.023962,0.131029,1.707697,0.009930,1.062488
9,(Banana),(Organic Avocado),0.240262,0.084122,0.027466,0.114317,1.358945,0.007255,1.034093
11,(Banana),(Organic Baby Spinach),0.240262,0.112425,0.026954,0.112188,0.997891,-0.000057,0.999733
14,(Banana),(Strawberries),0.240262,0.061449,0.022392,0.093196,1.516638,0.007628,1.035010

In [32]:
rules4.sort_values(['confidence','lift'], ascending=[False,False])[:20]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
15,(Strawberries),(Banana),0.061449,0.240262,0.022392,0.364390,1.516638,0.007628,1.195290
8,(Organic Avocado),(Banana),0.084122,0.240262,0.027466,0.326503,1.358945,0.007255,1.128049
4,(Organic Raspberries),(Bag of Organic Bananas),0.076729,0.182874,0.023962,0.312293,1.707697,0.009930,1.188189
2,(Organic Hass Avocado),(Bag of Organic Bananas),0.109360,0.182874,0.033962,0.310552,1.698179,0.013963,1.185190
6,(Organic Strawberries),(Bag of Organic Bananas),0.142823,0.182874,0.034470,0.241346,1.319742,0.008351,1.077074
10,(Organic Baby Spinach),(Banana),0.112425,0.240262,0.026954,0.239755,0.997891,-0.000057,0.999333
12,(Organic Strawberries),(Banana),0.142823,0.240262,0.032585,0.228147,0.949577,-0.001730,0.984304
0,(Organic Baby Spinach),(Bag of Organic Bananas),0.112425,0.182874,0.025378,0.225728,1.234340,0.004818,1.055348
16,(Organic Hass Avocado),(Organic Strawberries),0.109360,0.142823,0.023450,0.214431,1.501368,0.007831,1.091153
7,(Bag of Organic Bananas),(Organic Strawberries),0.182874,0.142823,0.034470,0.188490,1.319742,0.008351,1.056274
3,(Bag of Organic Bananas),(Organic Hass Avocado),0.182874,0.109360,0.033962,0.185714,1.698179,0.013963,1.093767
17,(Organic Strawberries),(Organic Hass Avocado),0.142823,0.109360,0.023450,0.164190,1.501368,0.007831,1.065601
1,(Bag of Organic Bananas),(Organic Baby Spinach),0.182874,0.112425,0.025378,0.138771,1.234340,0.004818,1.030591
13,(Banana),(Organic Strawberries),0.240262,0.142823,0.032585,0.135622,0.949577,-0.001730,0.991669
5,(Bag of Organic Bananas),(Organic Raspberries),0.182874,0.076729,0.023962,0.131029,1.707697,0.009930,1.062488
9,(Banana),(Organic Avocado),0.240262,0.084122,0.027466,0.114317,1.358945,0.007255,1.034093
11,(Banana),(Organic Baby Spinach),0.240262,0.112425,0.026954,0.112188,0.997891,-0.000057,0.999733
14,(Banana),(Strawberries),0.240262,0.061449,0.022392,0.093196,1.516638,0.007628,1.035010

In [18]:
rules4.to_csv('basket4.csv',index=False)

### Cluster 5 - Basket Analysis

In [40]:
prod_freq5 = cluster5.groupby('product_id')['order_id'].count().reset_index()
prod_freq5 = prod_freq5.rename(columns = {'order_id':'frequency'})
prod_freq5 = prod_freq5.sort_values('frequency', ascending=False).reset_index(drop=True)
prod_freq5 = prod_freq5.merge(products, on = 'product_id', how = 'left')

In [41]:
# only keeping the 100 most purchased products
prod_freq5 = prod_freq5[0:100]
prod_freq_prod5 = list(prod_freq5['product_id'])

In [42]:
# filter main cluster dataset only on the 100 most purchases products
cluster5 = cluster5[cluster5['product_id'].isin(prod_freq_prod5)]
print(cluster5.shape)
cluster5['product_id'].nunique()

(335134, 13)

100

In [43]:
basket_5 = cluster5.groupby(['order_id', 'product_name'])['reordered'].count().unstack().reset_index().fillna(0).set_index('order_id')

In [44]:
basket_5 = basket_5.applymap(encode_basket)

In [45]:
itemset5 = apriori(basket_5, use_colnames=True, verbose=1, min_support=0.004)

Processing 900 combinations | Sampling itemset size 4 3

In [46]:
itemset5

      support                                           itemsets
0    0.025897                         (0% Greek Strained Yogurt)
1    0.011303                                          (Almonds)
2    0.036798                                           (Apples)
3    0.120790                                   (Baby Cucumbers)
4    0.023824                       (Bag of Jumbo Yellow Onions)
..        ...                                                ...
527  0.004489  (Seedless Cucumbers, Rainbow Bell Peppers, Ras...
528  0.006502  (Strawberries, Rainbow Bell Peppers, Raspberries)
529  0.004962  (Strawberries, Seedless Cucumbers, Rainbow Bel...
530  0.006512    (Seedless Cucumbers, Strawberries, Raspberries)
531  0.004167  (Sweet Kale Salad Mix, Strawberries, Raspberries)

[532 rows x 2 columns]

In [47]:
rules5 = association_rules(itemset5, metric="lift", min_threshold=1)
rules5 = rules5.sort_values(['confidence','lift'], ascending=[False,False])
rules5.head(60)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
848,"(Blueberries, Blackberries)",(Raspberries),0.006401,0.184099,0.004469,0.698113,3.792047,0.003290,2.702671
874,"(Blackberries, Organic Blueberries)",(Raspberries),0.010528,0.184099,0.006371,0.605163,3.287153,0.004433,2.066422
854,"(Blackberries, Clementines)",(Raspberries),0.009371,0.184099,0.005586,0.596133,3.238107,0.003861,2.020222
890,"(Strawberries, Blackberries)",(Raspberries),0.017312,0.184099,0.009874,0.570349,3.098050,0.006687,1.898984
902,"(Blueberries, Strawberries)",(Raspberries),0.011565,0.184099,0.006079,0.525674,2.855386,0.003950,1.720128
656,"(Baby Cucumbers, Blackberries)",(Raspberries),0.009340,0.184099,0.004821,0.516164,2.803725,0.003102,1.686316
860,"(Hass Avocados, Blackberries)",(Raspberries),0.014534,0.184099,0.007448,0.512465,2.783636,0.004772,1.673524
186,(Blackberries),(Raspberries),0.062021,0.184099,0.031644,0.510224,2.771461,0.020226,1.665865
740,"(Bag of Organic Bananas, Blackberries)",(Raspberries),0.010961,0.184099,0.005546,0.505969,2.748347,0.003528,1.651517
200,(Blueberries),(Raspberries),0.034171,0.184099,0.016708,0.488954,2.655928,0.010417,1.596532
896,"(Blueberries, Hass Avocados)",(Raspberries),0.008938,0.184099,0.004247,0.475225,2.581353,0.002602,1.554764
880,"(Blackberries, Packaged Grape Tomatoes)",(Raspberries),0.010468,0.184099,0.004932,0.471154,2.559238,0.003005,1.542794
488,(Organic Blackberries),(Raspberries),0.014534,0.184099,0.006804,0.468144,2.542889,0.004128,1.534063
1071,"(Strawberries, Organic Blueberries)",(Raspberries),0.015762,0.184099,0.007277,0.461686,2.507809,0.004375,1.515659
1066,"(Organic Strawberries, Organic Blueberries)",(Raspberries),0.009773,0.184099,0.004288,0.438723,2.383078,0.002488,1.453651
928,"(Clementines, Organic Blueberries)",(Raspberries),0.009310,0.184099,0.004026,0.432432,2.348909,0.002312,1.437539
951,"(Green Seedless Grapes, Raspberries)",(Strawberries),0.010357,0.144534,0.004157,0.401361,2.776934,0.002660,1.429018
506,(Organic Blueberries Clamshell),(Raspberries),0.013407,0.184099,0.005304,0.395646,2.149088,0.002836,1.350037
813,"(Bag of Organic Bananas, Organic Blueberries)",(Raspberries),0.013698,0.184099,0.005355,0.390889,2.123251,0.002833,1.339494
674,"(Baby Cucumbers, Organic Baby Spinach)",(Hass Avocados),0.012652,0.211798,0.004942,0.390613,1.844268,0.002262,1.293433
886,"(Blackberries, Packaged Grape Tomatoes)",(Strawberries),0.010468,0.144534,0.004076,0.389423,2.694341,0.002563,1.401079
286,(Trail Mix),(Clementines),0.021006,0.136784,0.008153,0.388117,2.837452,0.005279,1.410754
499,(Organic Blueberries),(Raspberries),0.069127,0.184099,0.026632,0.385265,2.092702,0.013906,1.327240
950,"(Green Seedless Grapes, Strawberries)",(Raspberries),0.010890,0.184099,0.004157,0.381701,2.073341,0.002152,1.319588
1120,"(Rainbow Bell Peppers, Raspberries)",(Strawberries),0.017060,0.144534,0.006502,0.381121,2.636900,0.004036,1.382284
778,"(Bag of Organic Bananas, Packaged Grape Tomatoes)",(Hass Avocados),0.018751,0.211798,0.007106,0.378959,1.789244,0.003134,1.269162
1058,"(Strawberries, Organic Baby Spinach)",(Raspberries),0.015077,0.184099,0.005707,0.378505,2.055981,0.002931,1.312803
1102,"(Raspberries, Packaged Grape Tomatoes)",(Strawberries),0.022687,0.144534,0.008555,0.377107,2.609131,0.005276,1.373377
944,"(Strawberries, Clementines)",(Raspberries),0.022666,0.184099,0.008515,0.375666,2.040562,0.004342,1.306834
981,"(Hass Avocados, Organic Blueberries)",(Raspberries),0.015540,0.184099,0.005818,0.374352,2.033426,0.002957,1.304090
992,"(Hass Avocados, Organic Strawberries)",(Raspberries),0.013105,0.184099,0.004831,0.368664,2.002526,0.002419,1.292339
842,"(Strawberries, Bag of Organic Bananas)",(Raspberries),0.023904,0.184099,0.008797,0.368000,1.998921,0.004396,1.290982
903,"(Blueberries, Raspberries)",(Strawberries),0.016708,0.144534,0.006079,0.363855,2.517444,0.003664,1.344767
958,"(Organic Baby Spinach, Packaged Grape Tomatoes)",(Hass Avocados),0.014041,0.211798,0.005053,0.359857,1.699054,0.002079,1.231289
766,"(Bag of Organic Bananas, Organic Baby Spinach)",(Hass Avocados),0.017745,0.211798,0.006381,0.359614,1.697910,0.002623,1.230824
976,"(Strawberries, Organic Baby Spinach)",(Hass Avocados),0.015077,0.211798,0.005395,0.357810,1.689393,0.002201,1.227366
784,"(Bag of Organic Bananas, Rainbow Bell Peppers)",(Hass Avocados),0.014886,0.211798,0.005324,0.357674,1.688749,0.002172,1.227106
818,"(Bag of Organic Bananas, Organic Strawberries)",(Raspberries),0.011766,0.184099,0.004207,0.357571,1.942270,0.002041,1.270024
1046,"(Hass Avocados, Strawberries)",(Raspberries),0.036918,0.184099,0.013115,0.355234,1.929581,0.006318,1.265422
735,"(Baby Cucumbers, Raspberries)",(Strawberries),0.024307,0.144534,0.008626,0.354865,2.455244,0.005113,1.326028
704,"(Baby Cucumbers, Rainbow Bell Peppers)",(Packaged Grape Tomatoes),0.017423,0.111681,0.006180,0.354708,3.176071,0.004234,1.376615
1006,"(Raspberries, Packaged Grape Tomatoes)",(Hass Avocados),0.022687,0.211798,0.008042,0.354481,1.673673,0.003237,1.221036
1136,"(Sweet Kale Salad Mix, Strawberries)",(Raspberries),0.011786,0.184099,0.004167,0.353544,1.920398,0.001997,1.262113
796,"(Seedless Cucumbers, Bag of Organic Bananas)",(Hass Avocados),0.017171,0.211798,0.006049,0.352286,1.663310,0.002412,1.216898
802,"(Strawberries, Bag of Organic Bananas)",(Hass Avocados),0.023904,0.211798,0.008384,0.350737,1.655995,0.003321,1.213994
970,"(Seedless Cucumbers, Organic Baby Spinach)",(Hass Avocados),0.011947,0.211798,0.004157,0.347936,1.642771,0.001626,1.208780
1118,"(Strawberries, Rainbow Bell Peppers)",(Raspberries),0.018701,0.184099,0.006502,0.347686,1.888577,0.003059,1.250778
1131,"(Seedless Cucumbers, Raspberries)",(Strawberries),0.018791,0.144534,0.006512,0.346545,2.397678,0.003796,1.309144
867,"(Hass Avocados, Blackberries)",(Strawberries),0.014534,0.144534,0.004982,0.342798,2.371750,0.002882,1.301679
202,(Blueberries),(Strawberries),0.034171,0.144534,0.011565,0.338439,2.341592,0.006626,1.293102
1036,"(Strawberries, Rainbow Bell Peppers)",(Hass Avocados),0.018701,0.211798,0.006291,0.336383,1.588225,0.002330,1.187736
2,(0% Greek Strained Yogurt),(Clementines),0.025897,0.136784,0.008616,0.332686,2.432203,0.005073,1.293568
946,"(Clementines, Raspberries)",(Strawberries),0.025656,0.144534,0.008515,0.331895,2.296315,0.004807,1.280437
606,(Strawberries),(Raspberries),0.144534,0.184099,0.047970,0.331894,1.802800,0.021361,1.221215
910,"(Clementines, Packaged Grape Tomatoes)",(Hass Avocados),0.015802,0.211798,0.005244,0.331847,1.566808,0.001897,1.179673
542,(Organic Strawberries),(Raspberries),0.059082,0.184099,0.019587,0.331516,1.800747,0.008710,1.220524
609,(Red Seedless Grapes),(Strawberries),0.015671,0.144534,0.005194,0.331407,2.292936,0.002929,1.279501
632,"(Baby Cucumbers, Bag of Organic Bananas)",(Hass Avocados),0.022717,0.211798,0.007519,0.330970,1.562668,0.002707,1.178127
1100,"(Strawberries, Packaged Grape Tomatoes)",(Raspberries),0.025927,0.184099,0.008555,0.329969,1.792342,0.003782,1.217706
734,"(Baby Cucumbers, Strawberries)",(Raspberries),0.026209,0.184099,0.008626,0.329109,1.787672,0.003801,1.216145

In [46]:
rules5.to_csv('basket5.csv',index=False)

In [51]:
rules5[rules5['antecedents']==('Blueberries')]

Empty DataFrame
Columns: [antecedents, consequents, antecedent support, consequent support, support, confidence, lift, leverage, conviction]
Index: []

## Recommender

In [14]:
all_orders = pd.read_csv('cluster_all_orders.csv')
all_orders.shape

(32434489, 13)

In [27]:
list(all_orders['user_id'])[:3]

[202279, 202279, 202279]

In [32]:
user = input('Input the user_id here:')
# product = input('Input product_id here:')

user_ids = list(all_orders['user_id'])

for users in user_ids:
    if user == users:
        print('hello')
    #cluster = all_orders[all_orders['user_id']==user]
#     cluster_label = cluster['cluster'].value
    #print('hello')
#     if cluster_label == 0:
#         rule0[rule0['antecedents']==product]

Input the user_id here:202279

In [52]:
sample_orders = all_orders.sample(frac=0.45, replace=True, random_state=1)

In [53]:
sample_orders.to_csv('sample_all_orders.csv',index=False)